### ISSUE TITLE
Fix cabal build with-examples

### ISSUE THREAD

**Issue by greglaun-google** [awakesecurity/gRPC-haskell#112]
I'm unable to build the examples from master on a stock Ubuntu VM. I'm building using cabal rather than stack.

Most recently, the build was broken by PR #110, which upgraded proto3-wire and proto3-suite.

The version released on Hackage (https://hackage.haskell.org/package/grpc-haskell) also fails to build.

Steps to reproduce:

1. Grab an Ubuntu Groovy VM
1. Run 'sudo apt-get update`
1. Install Nix following https://nixos.org/download.html
1. `git clone https://github.com/awakesecurity/gRPC-haskell.git`
1. Run `nix-shell release.nix -A grpc-haskell.env`, which succeeds.
1. Run `cabal configure --enable-tests && cabal build && cabal test`, which succeeds.
1. Finally, run `cabal configure --enable-tests -f with-examples && cabal build && cabal test`

Expected result: Build succeeds.

Actual result: 

build fails with an error "The constructor ‘ServiceOptions’ should have 9 arguments, but has been given 8."

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/awakesecurity/gRPC-haskell/pull/115
