### ISSUE TITLE
Fix the stack build

### ISSUE THREAD

**Issue by greglaun-google** [awakesecurity/gRPC-haskell#113]
I'm unable to build the examples from master on a stock Ubuntu VM using Stack. I'm following the instructions on the README.

Steps to reproduce:

1. Grab an Ubuntu VM. I've tried several versions, including 20.10 and 18.04 LTS.
1. Run 'sudo apt-get update`
1. Generate an SSH key and upload it to GitHub. This step is required because stack.yaml uses GitHub urls that start with "git://", which forces the use to authenticate. This would be simplified if stack.yaml used the https GitHub urls.
1. Install Stack following https://docs.haskellstack.org/en/stable/install_and_upgrade/. I also tried older versions of Stack to try to build older commits.
1. Install Nix following https://nixos.org/download.html
1. `git clone https://github.com/awakesecurity/gRPC-haskell.git`
1. Run `nix-shell release.nix -A grpc-haskell.env`, which succeeds.
1. Run `stack build --fast && stack test --fast`, which fails.

 Expected result: Build succeeds.

Actual result:

build fails with an error

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for grpc-haskell-0.0.2.0:
    proto3-suite-0.4.0.0 from stack configuration does not match >=0.4.2.0 
    proto3-wire-1.1.0 from stack configuration does not match >=1.2.0  (latest matching version is 1.2.0)
needed since grpc-haskell is a build target.

```
It is straightforward to fix `stack build` by upgrading the dependencies in stack.yaml. However, `stack test` and `stack build --flag grpc-haskell:with-examples` both fail. Both complain about missing dependencies.

I tried installing various versions of grpc in the ambient OS (outside of the nix shell), but that did not help. For example, I tried gRPC 1.2 and gRPC 1.22 with various git commits.

I'm unable to make the instructions as written work with any combination of Stack, Ubuntu, and gRPC or any git commit. My guess is that when the Stack build works it's because it's pulling extra dependencies from the developers' machines, and those dependencies aren't explicitly modeled in the build configs.

**Comment by Gabriel439** [comment]
@greglaun-google: My personal inclination is to drop the `stack` support (unless somebody else is willing to maintain the `stack` instructions).  The Nix workflow requires less work for us to maintain, and it's what we use within our organization.

**Comment by greglaun-google** [comment]
Dropping stack support sounds good to me. Supporting multiple build systems sounds like a lot of overheard in general.

**Comment by Gabriel439** [comment]
The PR to drop `stack` support is up here: https://github.com/awakesecurity/gRPC-haskell/pull/116
