### ISSUE TITLE
Consider using a continuous build system

### ISSUE THREAD

**Issue by greglaun-google** [awakesecurity/gRPC-haskell#114]
It would be helpful to have a reproducible environment with a known good build. Without that, it can be difficult for developers to evaluate whether they want to use or contribute to gRPC-haskell.

It appears that GitHub now offers a free build service (https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/) for open source repositories.

You should be able to block pull requests using this service, so that no PR can be submitted unless the build is successful. See https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-required-status-checks.

The build script can be as simple as just running the stack build or cabal build commands from the README. I recommend building with examples, since most newcomers to the project will want to see the examples first.

If you want to get fancier, you can consider using Bazel, which appears to be better for hermetic builds than Stack or Nix alone. See for example https://www.tweag.io/blog/2018-03-15-bazel-nix/.

**Comment by Gabriel439** [comment]
Fixed by https://github.com/awakesecurity/gRPC-haskell/pull/64
