### ISSUE TITLE
Hackage version 0.1.0 requires a missing proto3-suite 0.4.2.0 release

### ISSUE THREAD

**Issue by TristanCacqueray** [awakesecurity/gRPC-haskell#122]
It seems like the grpc-haskell-0.1.0 published on hackage can't be installed because there is no proto3-suite>=0.4.2.0 available there.

**Comment by TristanCacqueray** [comment]
The culprit might be https://github.com/awakesecurity/proto3-suite/pull/144 . Using the commit before that change works, e.g. with this `cabal.project`:

```cabal
source-repository-package
  type: git
  location: https://github.com/awakesecurity/proto3-suite
  tag: 0af901f9ef3b9719e08eae4fab8fd700d6c8047a

source-repository-package
  type: git
  location: https://github.com/awakesecurity/gRPC-haskell
  tag: 1bdc3662db13686f5e4941f3cc506f6fdf11ce32
```

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/awakesecurity/gRPC-haskell/issues/122
