### ISSUE TITLE
Usage (No Constructor imported)

### ISSUE THREAD

**Issue by MohsenNz** [awakesecurity/gRPC-haskell#162]
Hello there.
I configured my project for using grpc-haskell (in cabal, not nix). But after I tried to use example arithmetic (I copied the files and directory to my own project) I encountered these errors:
![Screenshot from 2024-03-15 02-44-14](https://github.com/awakesecurity/gRPC-haskell/assets/23291352/eded8868-b9c5-4624-9a0b-3964268aa082)
It say it needed type constructor Arithmetic. After I import that, I encountered:
![Screenshot from 2024-03-15 02-44-56](https://github.com/awakesecurity/gRPC-haskell/assets/23291352/504c4f0d-812c-48d7-a428-cfc477cbb55f)
It says Arithmetic constructor is not exported. Then I checked the generated file `Arithmetic.hs`:
![Screenshot from 2024-03-15 02-45-18](https://github.com/awakesecurity/gRPC-haskell/assets/23291352/b8bee305-6579-42bd-94f6-7ce43e6af86c)
Here there is no data exported. I'm wondering how to use it ?

**Comment by MohsenNz** [comment]
OK, it was my mistake. I wasn't in my development shell (nix develop). After entering that the problem solved. 
Anyway, I still had a question how Arithmetic constructor and other stuff are importable will they are not exported in Arithmetic.hs ? (I'm newbie in Haskell and will thankful for putting up with me)

**Comment by ixmatus** [comment]
@MohsenNz if there are no explicit exports from a module, then everything is exported, which is the case with `module Arithmetic where`. The haskell.org website has what looks like a good tutorial on modules: https://www.haskell.org/tutorial/modules.html.

If you are new to Haskell, I recommend starting your learning journey with something simpler that has better tutorial materials for beginners like Servant for web applications.
