### ISSUE TITLE
Handle State

### ISSUE THREAD

**Issue by MohsenNz** [awakesecurity/gRPC-haskell#165]
Can we handle state in RPC functions ? 
E.g I have this service :
```proto
service PhoneAuthService {
  rpc Login(LoginRequest) returns (LoginResponse);
}

message LoginRequest {
  string phone_number = 1;
}

message LoginResponse {
  string verification_code = 1;
}
```

And here is my code :

```Haskell
handlers :: PhoneAuthService ServerRequest ServerResponse
handlers =
    PhoneAuthService
        { phoneAuthServiceLogin = loginHandler
        }

loginHandler
    :: ServerRequest 'Normal LoginRequest LoginResponse
    -> IO (ServerResponse 'Normal LoginResponse)
loginH (ServerNormalRequest _ (LoginRequest phoneNumber)) = do
    vcode <- generateVerificationCode 6
    let resp = LoginResponse vcode
    pure $ ServerNormalResponse resp [] StatusOk ""
```

In function `loginHandler` I want to store `phoneNumber` in a state (in-memory or any database), but I think with the type signature of this function It's not possible.

**Comment by riz0id** [comment]
I suggest you familiarize yourself with [Data.IORef](https://hackage.haskell.org/package/base-4.19.1.0/docs/Data-IORef.html).

**Comment by MohsenNz** [comment]
Thanks a lot.

**Comment by ixmatus** [comment]
@MohsenNz please reserve this repository's issues for bugs or feature requests regarding `gRPC-haskell`. If you need help with Haskell and how to implement things in Haskell, please post questions to StackOverflow or Haskell Discord.
