### ISSUE TITLE
Is the library thread-safe?

### ISSUE THREAD

**Issue by OlivierNicole** [awakesecurity/gRPC-haskell#25]
I read the following in the core gRPC header (`grpc/grpc.h`):

> THREAD SAFETY: access to grpc_call_start_batch in multi-threaded environment
>     needs to be synchronized. As an optimization, you may synchronize batches
>     containing just send operations independently from batches containing just
>     receive operations

But I haven't noticed such precautions being taken while (briefly) reading the code of grpc-haskell. So my question is: is the library thread-safe, i.e. can all high-level functions (like making requests, etc.) be used without any synchronization?

Thanks.

**Comment by crclark** [comment]
Everything above the `Unsafe` level, except for `Network.GRPC.LowLevel.CompletionQueue.Internal`,  should be thread-safe. The only synchronization used before calling `grpc_call_start_batch` is for the completion queue, not the call to `grpc_call_start_batch` itself. So we might have a bug. I do remember seeing that warning and I remember doing *something* about it, but I can't remember what, if anything, I did. I suspect that the warning may only apply if you call `grpc_call_start_batch` on the same `grpc_call` from multiple threads, which our library never does.

If this is a bug, it hasn't been a problem in practice so far (though that's not very reassuring for a possible thread safety issue!). I've benchmarked the library by sending and receiving many calls in parallel on many threads, and the benchmark never exhibited any instability.

**Comment by crclark** [comment]
Reading through the C++ implementation, I actually can't find any synchronization on either `grpc_call_start_batch`, or on `grpc_completion_queue_pluck`, yet in a [couple](https://github.com/grpc/grpc/issues/5649) [issues](https://github.com/grpc/grpc/issues/4486), they state that the C++ library is thread safe. Puzzling.

**Comment by OlivierNicole** [comment]
Thanks for your answers. Just wanted to check. I did have a thread-safety problem, but it turned out to be due to me, not to your library.

**Comment by Gabriel439** [comment]
So should we close this issue, then?

**Comment by OlivierNicole** [comment]
Yes, sorry. I got what I wanted.
