### ISSUE TITLE
Proposal: split out a `gRPC-haskell-lowlevel` package

### ISSUE THREAD

**Issue by judah** [awakesecurity/gRPC-haskell#38]
We are interested in using `gRPC-haskell` with [proto-lens](https://github.com/google/proto-lens) (specifically, the GRPC low-level API).  One of the main blockers for adding such functionality into `proto-lens` itself is that `gRPC-haskell` depends on `proto3-suite` which overlaps with the functionality of `proto-lens`.

I propose the following changes:

- Move `Network.GRPC.{LowLevel,Unsafe}` to another package named `gRPC-haskell-lowlevel` (or something else), located within this same repository
- Optionally, use [reexported-modules](https://ghc.haskell.org/trac/ghc/wiki/ModuleReexports) to reexport those modules in the `gRPC-haskell` package itself, for backwards compatibility.

I can create and send a PR with those changes, but wanted to check in first; please let me know whether that approach sounds reasonable.

**Comment by Gabriel439** [comment]
Yes, we welcome this!  Thank you for offering to do this

**Comment by clavoie-takt** [comment]
You have any preferences as to how this should be done? I'm thinking just creating a gRPC-haskell-lowlevel package as a subdir and keep gRPC-haskell toplevel in the repo. Anything I need to keep in mind during the surgery?

**Comment by intractable** [comment]
Seems like a pretty reasonable approach to me. 

One minor suggestion is to name the low-level package  `grpc-haskell-core` or somesuch to indicate that it's a binding to the GRPC C core.

Thanks for taking this on! Happy cutting & suturing.

**Comment by intractable** [comment]
Addressed by https://github.com/awakesecurity/gRPC-haskell/pull/42
