### ISSUE TITLE
grpc build fails when using nix-channel 17.09

### ISSUE THREAD

**Issue by hiroqn** [awakesecurity/gRPC-haskell#44]
I have a Haskell project being built with nix, which depends on gRPC-haskell.
It can be built with nix-channel 17.03, the build fails with 17.09 and this nix file.
https://github.com/awakesecurity/gRPC-haskell/blob/f0925d5b5f4dff79d5f09d4a4aebc3babd9f1495/nix/grpc.nix

We get this error: https://github.com/grpc/grpc/issues/6925

and I noticed [Gabriel's comment](https://github.com/grpc/grpc/issues/6925#issuecomment-355720526).

But I got another error about the linker, which claims `ld` has no `-pthread` option.
`

Finally, I changed nix file to as below, then build succeeds.

```
{ pkgs, stdenv, lib, fetchgit, autoconf, automake, libtool, which, zlib, openssl
}:

stdenv.mkDerivation rec {
  name    = "grpc-${version}";
  version = "1.2.0-${lib.strings.substring 0 7 rev}";
  rev     = "e2cfe9df79c4eda4e376222df064c4c65e616352";
  src = fetchgit {
    inherit rev;
    url    = "https://github.com/grpc/grpc.git";
    sha256 = "19ldbjlnbc287hkaylsigm8w9fai2bjdbfxk6315kl75cq54iprr";
  };
  makeFlags = [ "prefix=$(out)" "AROPTS=rcs" "LD=gcc"];
  buildInputs =
    (if stdenv.isDarwin then [ pkgs.darwin.cctools ] else []) ++ [
    autoconf
    automake
    libtool
    which
    zlib
    openssl
  ];
}
```

**Comment by Gabriel439** [comment]
Yeah, we just upgraded to Nixpkgs 17.09 internally yesterday and ran into the same issue.  This is the new derivation that we came up with:

```nix
{ darwin, stdenv, lib, fetchgit, autoconf, automake, libtool, which, zlib
, openssl
}:

stdenv.mkDerivation rec {
  name    = "grpc-${version}";
  version = "1.2.0-${lib.strings.substring 0 7 rev}";
  rev     = "e2cfe9df79c4eda4e376222df064c4c65e616352";
  src = fetchgit {
    inherit rev;
    url    = "https://github.com/grpc/grpc.git";
    sha256 = "19ldbjlnbc287hkaylsigm8w9fai2bjdbfxk6315kl75cq54iprr";
  };

  # `grpc`'s `Makefile` does some magic to detect the correct `ld` and `strip`
  # to use along with their flags, too.  If Nix supplies `$LD` and `$STRIP` then
  # this auto-detection fails and the build fails, which is why we unset the
  # environment variables here and let the `Makefile` set them.
  preBuild = ''
    unset LD
    unset STRIP
  '';

  preInstall = "export prefix";

  buildInputs = [
    autoconf
    automake
    libtool
    which
    zlib
    openssl
  ];

  # Some versions of `ar` (such as the one provided by OS X) require an explicit
  # `-r` flag, whereas other versions assume `-r` is the default if no mode is
  # specified.  For example, OS X requires the `-r` flag, so as a precaution we
  # always specify the flag.
  AROPTS = "-r";
}
```

 We just haven't updated the open source derivation, but I can do that right now

**Comment by Gabriel439** [comment]
Looks like @shlevy beat us to it.  There is a `grpc` derivation for a much newer version added 10 days ago: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/grpc/default.nix

Let me see how difficult it is to upgrade to that derivation

**Comment by Gabriel439** [comment]
So this is slightly fixed in that I've updated the `grpc` derivation to be 17.09-compatible but it's still on an old version of `gRPC`.  I will do a second pass later to update to the more recent `grpc` that has been upstreamed into `nixpkgs`

**Comment by shlevy** [comment]
Do you want me to backport that to 17.09 channel?

**Comment by Gabriel439** [comment]
@shlevy: Oh, I didn't realize it wasn't in 17.09.  Yes, if you could we would really appreciate it

**Comment by shlevy** [comment]
grpc builds in 17.09 as of aaa4cd02d96bf2d1110be08a68eb68a9187e94cb

**Comment by Gabriel439** [comment]
@shlevy: Thank you! :)

**Comment by cocreature** [comment]
I think this is probably outdated now. We’ve upgraded both nixpkgs and gRPC.

**Comment by Gabriel439** [comment]
Yeah, I'll close this since I believe it is addressed by the recent upgrades
