### ISSUE TITLE
Generated Files No Longer Compile After Core Separation

### ISSUE THREAD

**Issue by isheff** [awakesecurity/gRPC-haskell#53]
The generated files still feature the line:

`import Network.GRPC.LowLevel.Call as HsGRPC`

But that package no longer exists.

**Comment by intractable** [comment]
Thank you for pointing this out. I'll fix it.

**Comment by intractable** [comment]
@isheff Oh, sorry -- it exists, but it's been moved to the `grpc-haskell-core` library, so you may need to add that dependency explicitly in your own code. Let me know if you've a repro case that's causing you pain and I'll investigate further.

**Comment by isheff** [comment]
Indeed adding `grpc-haskell-core` as a dependency works. However, so does changing the lines from the generated source code:
```
import Network.GRPC.HighLevel.Server.Unregistered as HsGRPC
       (serverLoop)
import Network.GRPC.LowLevel.Call as HsGRP
```
to:
```
import Network.GRPC.HighLevel.Server.Unregistered as HsGRPC
```

If this indeed works in general, perhaps this is a better solution.

**Comment by Gabriel439** [comment]
Pull request up to fix this in https://github.com/awakesecurity/proto3-suite/pull/58
