### ISSUE TITLE
How to disable tests when doing "nix-shell release.nix -A grpc-haskell.env"

### ISSUE THREAD

**Issue by tomoyat1** [awakesecurity/gRPC-haskell#59]
Hi,

I am trying to get this library to work with the lates grpc release, but I need to debug a SIGSEGV.

I'd like to go into a `nix-shell` and mess around with things, but `nix-shell` will fail because the unit tests SIGSEGV.

How would I disable the unit tests when starting the `nix-shell`?

I'm not familiar with Nix. I only know the basic concepts to some extent.
Any help is appreciated. Sorry if this is the wrong place to post.

**Comment by ixmatus** [comment]
You can launch a nix-shell for the don't check derivation variant instead:

```
$ nix-shell --attr grpc-haskell-no-tests ./release.nix
```

**Comment by tomoyat1** [comment]
@ixmatus I tried that, but the tests ran nontheless.

**Comment by tomoyat1** [comment]
@ixmatus 

Here's a [gist](https://gist.github.com/tomoyat1/9129d1dd963e402df7da9843e40b7c43) of the logs, as well as the output of `git diff`

**Comment by Gabriel439** [comment]
@tomoyat1: Are you sure that you tried running exactly the command: `nix-shell --attr grpc-haskell-no-tests.env ./release.nix`?  Your gist doesn't include the command that you ran

I also tested `nix-shell --attr grpc-haskell-no-tests.env ./release.nix` myself and it didn't run any tests

**Comment by tomoyat1** [comment]
@Gabriel439 
I did a fresh `git clone` of the repo, copy and pasted the command, and the tests still ran (and passed) on my box. 
When I exit the nix-shell and run the command a second time, the tests don't run.

**Comment by Gabriel439** [comment]
@tomoyat1: Are you sure that the tests that you observed were for the `gRPC-haskell` package and not tests for one of its dependencies?

**Comment by tomoyat1** [comment]
@Gabriel439 
```
Preprocessing test suite 'tests' for grpc-haskell-core-0.0.0.0...                           
[1 of 4] Compiling UnsafeTests      ( tests/UnsafeTests.hs, dist/build/tests/tests-tmp/Unsaf
eTests.dyn_o )                                                                              
[2 of 4] Compiling LowLevelTests.Op ( tests/LowLevelTests/Op.hs, dist/build/tests/tests-tmp/
LowLevelTests/Op.dyn_o )                                                                    
[3 of 4] Compiling LowLevelTests    ( tests/LowLevelTests.hs, dist/build/tests/tests-tmp/Low
LevelTests.dyn_o )                                                                          
[4 of 4] Compiling Main             ( tests/Properties.hs, dist/build/tests/tests-tmp/Main.d
yn_o )                                                                                      
Linking dist/build/tests/tests ...                                                          
running tests                                                                               
Running 1 test suites...                                                                    
Test suite tests: RUNNING...                                                                
GRPC Unit Tests                                                                             
  Unit tests for unsafe C bindings                                                          
---------- a bunch of passing test cases which I have omitted here -----------
  Synchronous unit tests of low-level Op interface
    Client/Server - client receives server cancellation:                        tests: SignalException 11
Test suite tests: FAIL
Test suite logged to: dist/test/grpc-haskell-core-0.0.0.0-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
```

This is what I get. I'm think these are the tests for `gRPC-haskell`

**Comment by Gabriel439** [comment]
@tomoyat1: Those are the tests for `gRPC-haskell-core` (a lower-level library within the same repository that `gRPC-haskell` depends on).  So it's expected for those tests to build when initializing the shell for the first time or changing any dependency of `gRPC-haskell-core`

However, you can still disable those tests if you want.  To do so, modify `release.nix` and change this part:

```
          grpc-haskell-core =
            usesGRPC (haskellPackagesNew.callPackage ./core { });
```

... to:

```
          grpc-haskell-core =
            usesGRPC (pkgs.haskell.lib.dontCheck (haskellPackagesNew.callPackage ./core { }));
```

**Comment by tomoyat1** [comment]
@Gabriel439 
The tests didn't run, and I have a nix-shell.
Thank you so much for your help and patience!

**Comment by Gabriel439** [comment]
@tomoyat1: You're welcome! 🙂
