### ISSUE TITLE
Comment causes nix build to fail

### ISSUE THREAD

**Issue by dsvensson** [awakesecurity/gRPC-haskell#60]
Until I removed the following comment...

https://github.com/awakesecurity/gRPC-haskell/blob/master/src/Network/GRPC/HighLevel/Client.hs#L58

...the following command failed...

    nix-shell release.nix -A grpc-haskell.env

...with this output...

```
Preprocessing library grpc-haskell-0.0.0.0...
Preprocessing library grpc-haskell-0.0.0.0...
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: fail-4.9.0.0, swagger2-2.1.6

src/Network/GRPC/HighLevel/Client.hs:58:5: error:
    parse error on input ‘-- ^ The final field will be invoked once, and it should repeatedly
import Network.GRPC.LowLevel.Op (WritesDone)
    -- invoke its final argument (of type @(StreamRecv response)@)
    -- in order to obtain the streaming response incrementally.’
Haddock coverage:
   3% (  1 / 30) in 'Network.GRPC.HighLevel.Server'
  Missing documentation for:
```

Using nix-shell (Nix) 2.0.4, and a fresh checkout of gRPC-haskell on a fully up-to-date macOS.

**Comment by Gabriel439** [comment]
Fixed by https://github.com/awakesecurity/gRPC-haskell/commit/9c6b3f63b639e3febfc89327e6e698a0ed536d96
