### ISSUE TITLE
Document reason for staying on 1.2.0

### ISSUE THREAD

**Issue by dsvensson** [awakesecurity/gRPC-haskell#62]
gRPC is at 1.12, on its way to 1.13. It would be valuable to know _why_ the recommended version is still 1.2.0. Maybe some travis setup could build against both 1.2.0, and latest?

**Comment by ixmatus** [comment]
We simply have not had the time to update gRPC-core to make sure it works, we want to do that but it has lower priority in our organization at the moment compared to other things.

**Comment by cocreature** [comment]
Master is now on gRPC 1.22.

**Comment by cocreature** [comment]
Closing since master has switched to gRPC 1.22.
