### ISSUE TITLE
cannot stack build with grpc 1.4.3

### ISSUE THREAD

**Issue by shapr** [awakesecurity/gRPC-haskell#66]
I'd like to use gRPC-haskell to write tests at my job where we use protobuf 3.3 and grpc 1.4.3
After building and installing those from source, stack build gives me an error:

`    src/Network/GRPC/Unsafe.chs:229: (column 7) [ERROR]  >>> Unknown identifier!`
`      Cannot find a definition for grpc_call_destroy in the header file.`
`    src/Network/GRPC/Unsafe.chs:146: (column 3) [ERROR]  >>> Function arity mismatch!`
`      Parameter marshallers are missing.`

How could I fix this?

**Comment by Gabriel439** [comment]
This is because `gRPC_haskell` expects an older version of the `grpc` library and needs some work to support the latest version.  You can see the exact version of `grpc` that this package assumes here:

https://github.com/awakesecurity/gRPC-haskell/blob/master/nix/grpc.nix

**Comment by shinzui** [comment]
Is there any work being done to support new versions of gRPC?

**Comment by ixmatus** [comment]
@shinzui we have not done any work lately to support newer versions, I may try tackling that in the upcoming weeks.

**Comment by dariooddenino** [comment]
Hi, is there any update on this issue?

**Comment by ixmatus** [comment]
@dariooddenino no new updates, we haven't had time to work on this during work hours or personal time.

**Comment by dariooddenino** [comment]
@ixmatus I see, thanks. I might give a try at updating it if I decide to use haskell for this thing I need to do

**Comment by cocreature** [comment]
Master is now on gRPC 1.22.

**Comment by cocreature** [comment]
Closing since this has been addressed on master.
