### ISSUE TITLE
Upgrading gRPC-haskell to newer gRPC versions

### ISSUE THREAD

**Issue by cocreature** [awakesecurity/gRPC-haskell#83]
Hi, first of all thank for the great work on the bindings! We use them quite heavily in https://github.com/digital-asset/daml.

However, since we use the latest version of gRPC (1.22 at this point), we had to fork and patch the library. You can find our current state at https://github.com/digital-asset/daml/tree/master/nix/third-party/gRPC-haskell.

We would love to upstream our work but before doing so, it would be great to agree on the way forward:

1. Are you in general open to moving to a newer version of gRPC? #62 suggests so but it would be great if you could confirm that this is still the case. If so, do you need/want grpc-haskell to be compatible with older versions as well? If so, how far back?

2. Judging from the issues and pull requests on this repo, in particular, #80 it looks like the nixpkgs config is quite outdated at this point and fixing it seems to be a nontrivial task. Would you be open to moving to something “simpler”, e.g. a `cabal new-build` based setup for CI on this repo? If not, what is the best way to move this forward? Just hack on #80 until all tests pass?

3. Would you be interested in sharing the maintenance load on gRPC-haskell with people outside of Awake Security? Since we have a vested interest in gRPC-haskell, we would be happy to help making sure that it stays up2date after we’ve upstreamed our current patches.

cc @hurryabit @nickchapman-da

**Comment by ixmatus** [comment]
@cocreature we would be very happy to have you upstream your patches (thank you!)

1. We are open to moving to newer versions of gRPC, we simply have not done that work. We do not need it to be compatible with older versions because if we have a compatibility problem we can use an older git revision.
2. It is definitely out-dated but shouldn't take much time to make current and we can continue using an old git-rev if we need to. We prefer the Nix/nixpkgs workflow and we can also support cabal new-build inside of nix-shell environments.
3. Yes we are interested in sharing the maintenance work load, I will discuss with my colleagues for confirmation.

**Comment by cocreature** [comment]
Thanks for the response. I’ll try to get the nixpkgs upgrade done first and then upstream the rest afterwards.

**Comment by cocreature** [comment]
The nixpkgs upgrade is in #84

**Comment by cocreature** [comment]
We’ve upstreamed all of our patches, upgraded nixpkgs and @Gabriel439 has made me a contributor. Thanks for the quick responses!

The only thing left is a Hackage release of grpc-haskell and grpc-haskell-core and I believe we also need a Hackage release of proto3-suite and proto3-wire for that as grpc-haskell is currently tracking HEAD for those. If you have some time, it would be great if you could cut those releases (the current releases are missing the header which I fixed in #88 so they aren’t usable in any way afaict). Thanks!

**Comment by heath** [comment]
@Gabriel439 Pinging you as requested in Slack

**Comment by Gabriel439** [comment]
@cocreature @heath: Sorry for the delay.  I just released:

* `proto3-wire-1.1.0`
* `proto3-suite-0.4.0.0`
* `grpc-haskell-core-0.0.0.0`
* `grpc-haskell-0.1.0.0`

... so everything necessary should be on Hackage now.

Also, for future reference, I can add people as Hackage co-maintainers if you all need to cut releases without blocking on us

**Comment by cocreature** [comment]
Thanks a lot @Gabriel439! Closing this issue as it has all been addressed now :tada:

**Comment by Gabriel439** [comment]
@cocreature: You're welcome! 🙂
