### ISSUE TITLE
"pointer being freed was not allocated" when accepting a request

### ISSUE THREAD

**Issue by neongreen** [awakesecurity/gRPC-haskell#91]
_Continuing the discussion from #89._

A project (small gRPC server with one method) crashes when accepting a request from a gRCP client. At the moment I don't have a minimal example, but I'll see what I can do about it.

Since the error does not appear in a branch that is equivalent to `master` minus PR #90, I believe that it is caused by PR #90. The error is as follows:

```
projectname(2509,0x70000b9b1000) malloc: *** error for object 0x7f98d3c0cae0: pointer being freed was not allocated
projectname(2509,0x70000b9b1000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by cocreature** [comment]
Hm, maybe gRPC frees this internally somewhere? We definitely do allocate this afaict, see https://github.com/awakesecurity/gRPC-haskell/blob/be70fc49b0dc25313f57d0e6c6ba2a9fa46b9e6b/core/cbits/grpc_haskell.c#L70. I made the change when I was looking through the code not based on an actual failure that we encountered so I wouldn’t mind a revert but we should try to figure out why this is incorrect. At least to me, this definitely looks like a leak.

**Comment by cocreature** [comment]
Here is a usage example from `gRPC` which also seems to unref the slice so that doesn’t seem to be problematic in principle https://github.com/grpc/grpc/blob/7564664f077cdaa720451633107352cb39e233e4/src/csharp/ext/grpc_csharp_ext.c#L820,L849

**Comment by neongreen** [comment]
I tried debugging it but I might be doing something wrong because I don't see two `free`s:

```
project(31698,0x70000599c000) malloc: *** error for object 0x107d01f20: pointer being freed was not allocated
project(31698,0x70000599c000) malloc: *** set a breakpoint in malloc_error_break to debug
Process 31698 stopped
* thread #2, stop reason = breakpoint 1.1
    frame #0: 0x00007fff6c228972 libsystem_malloc.dylib`malloc_error_break
```

```
(lldb) malloc_info --stack-history 0x107d01f20

0x0000000107d01f20: malloc(    32) -> 0x107d01f20
stack[0]: addr = 0x107d01f20, type=malloc, frames:
     [0] 0x00007fff6c212cbd libsystem_malloc.dylib`malloc_zone_malloc + 139
     [1] 0x00007fff6c212c15 libsystem_malloc.dylib`malloc + 24
     [2] 0x0000000101e7625d libHSgrpc-haskell-core-0.0.0.0-2f4dmfF7wk4I7Kro0Zgt2a-ghc8.6.5.dylib`grpc_slice_from_copied_buffer_ + 29
     [3] 0x0000000101dcff13 libHSgrpc-haskell-core-0.0.0.0-2f4dmfF7wk4I7Kro0Zgt2a-ghc8.6.5.dylib`cb4t_info + 91
     [4] 0x70000599c001

stack[1]: addr = 0x107d01f20, type=free, frames:
     [0] 0x00007fff6c2159c9 libsystem_malloc.dylib`free + 400
     [1] 0x0000000101e767d4 libHSgrpc-haskell-core-0.0.0.0-2f4dmfF7wk4I7Kro0Zgt2a-ghc8.6.5.dylib`op_array_destroy + 116
     [2] 0x0000000101e509c1 libHSgrpc-haskell-core-0.0.0.0-2f4dmfF7wk4I7Kro0Zgt2a-ghc8.6.5.dylib`c1Ewn_info + 25
     [3] 0x70000599c001

stack[2]: addr = 0x107d01f20, type=malloc, frames:
     [0] 0x00007fff6c212cbd libsystem_malloc.dylib`malloc_zone_malloc + 139
     [1] 0x00007fff6a8899f0 libobjc.A.dylib`NXCreateHashTableFromZone + 39
     [2] 0x00007fff6a8899c0 libobjc.A.dylib`NXCreateHashTable + 47
     [3] 0x00007fff6a8a13ae libobjc.A.dylib`objc_class::demangledName() + 230
     [4] 0x00000001091e375b __lldb_apple_objc_v2_get_shared_cache_class_info`__lldb_apple_objc_v2_get_shared_cache_class_info(void*, void*, unsigned int, unsigned int) + 1195 at Parse:159
     [5] 0x00000001091e3c8b __lldb_caller_function`::__lldb_caller_function(void *) + 59 at Parse:13
     [6] 0x0000000100002f70 project`main
     [7] 0x00007fff6c21be38 libsystem_malloc.dylib`malloc_report + 151
     [8] 0x0000000101dcfcb7 libHSgrpc-haskell-core-0.0.0.0-2f4dmfF7wk4I7Kro0Zgt2a-ghc8.6.5.dylib`cb1u_info + 15
     [9] 0x70000599c001
```

**Comment by cocreature** [comment]
@neongreen Have you made any progress here? If you can provide a testcase I might be able to take a look (but not sure when I’ll get around to it). Without that it’s a bit hard to say what’s going wrong.

**Comment by neongreen** [comment]
I'll be able to provide it when the project is open-sourced.

**Comment by neongreen** [comment]
@cocreature 

The project has been open-sourced. I removed all irrelevant parts and got it down to a gRPC server with one method + one protobuf file.

```
git clone --single-branch -b artyom/grpc https://github.com/juspay/fencer
cd fencer
nix-build
result/bin/fencer
```

You'll need [grpcurl](https://github.com/fullstorydev/grpcurl) or another gRPC tool to submit the request. Assuming you have it installed:

```
grpcurl -proto proto/rls.proto -plaintext localhost:50051 envoy.service.ratelimit.v2.RateLimitService.ShouldRateLimit
```

The server will produce a response and then crash with a segfault.

**Comment by cocreature** [comment]
Thanks, I’ll see if I can find some time to look into this.

**Comment by neongreen** [comment]
Still crashes with grpc-1.23.1 (released today).

**Comment by neongreen** [comment]
I have also significantly minimized the example further. It fits into a comment now:

```proto
// protobuf

syntax = "proto3";

package envoy.service.ratelimit.v2;

service RateLimitService {
  rpc ShouldRateLimit(RateLimitRequest) returns (RateLimitResponse) {
  }
}

message RateLimitRequest {
  string domain = 1;
}

message RateLimitResponse {
  int64 overall_code = 1;
}
```

```haskell
-- Haskell

main :: IO ()
main = do
    let handlers = Proto.RateLimitService
            { Proto.rateLimitServiceShouldRateLimit = shouldRateLimit
            }
    let options = Grpc.defaultServiceOptions
    Proto.rateLimitServiceServer handlers options

shouldRateLimit
    :: Grpc.ServerRequest 'Grpc.Normal Proto.RateLimitRequest Proto.RateLimitResponse
    -> IO (Grpc.ServerResponse 'Grpc.Normal Proto.RateLimitResponse)
shouldRateLimit (Grpc.ServerNormalRequest _metadata _request) = do
    let answer = Proto.RateLimitResponse
            { Proto.rateLimitResponseOverallCode = 1
            }
    pure $ Grpc.ServerNormalResponse answer mempty Grpc.StatusOk ""
```

**Comment by neongreen** [comment]
@cocreature 

In `opArrayDestroy` we free the metadata and status details for all items in the array:

https://github.com/awakesecurity/gRPC-haskell/blob/master/core/cbits/grpc_haskell.c#L224-L228

We do the same in `freeOpContext`:

https://github.com/awakesecurity/gRPC-haskell/blob/master/core/src/Network/GRPC/LowLevel/Op.hs#L111-L112

And then in `withOpArrayAndCtxts` we call both:

https://github.com/awakesecurity/gRPC-haskell/blob/master/core/src/Network/GRPC/LowLevel/Op.hs#L134-L135

This seems wrong. Am I missing something?

**Comment by cocreature** [comment]
Good catch, thanks for tracking this down! This is definitely off. I believe that `freeSlice` is the proper thing to use here as it also takes care of calling `grpc_slice_unref` so the fix here seems to be to remove it from `opArrayDestroy`. However, I’m a bit unclear on what the split between `opArrayDestroy` and `freeOpContext` is supposed to be. Maybe @Gabriel439 or @ixmatus can weigh in on that?

**Comment by neongreen** [comment]
Ping. Is there something I can do to help with this issue? The split between `opArrayDestroy` and `freeOpContext` is unclear to me as well. If I knew what is the intended semantics of these functions, I could make a PR.

**Comment by Gabriel439** [comment]
@neongreen: Sorry, we're a bit swamped at the moment, but part of the reason we're slow to respond is that the person who wrote this code left the company a while ago, so we're also re-learning the semantics of the `grpc` package, too
