### ISSUE TITLE
format of `packages` in stack.yaml seems to be older one

### ISSUE THREAD

**Issue by Cj-bc** [awakesecurity/gRPC-haskell#92]
Firstly, thanks to maintaining gRPC-haskell.
I'm new to here as well as Haskell, so I'm sorry if there's some misunderstanding of them in this issue.

While I'm tried to use gRPC-haskell with `stack`, stack complained that yaml format is not correct.
It seems that the format of `packages` is changed in somewhere after stack 1.11, according to below information:
http://docs.haskellstack.org/en/stable/yaml_configuration/#packages
I modified stack.yaml for a bit and stack works correctly(I have [the commit on my fork](https://github.com/Cj-bc/gRPC-haskell/commit/7e3385d5445aebb7191a57f67458ff68927a0b31))
Just move some items from `packages` to `extra-deps`

**Comment by Gabriel439** [comment]
@Cj-bc: Yeah, we'd welcome a commit to change to the new format if you want

**Comment by Cj-bc** [comment]
Thanks!
I opened PR #93 .

**Comment by Cj-bc** [comment]
Thanks for merge!
